Feature: ePubReader
	In order to read books
	As a computer user
	I want to be able to view the content of an ePub file

Background: 
	Given I have set the file system

Scenario Outline: Get ePub title                                                                                                                                                    
	Given an ePub file named "<filename>"                                                                                                                                         
	When I open the file using ePubReader                                                                                                                                           
	Then the title is "<title>"                                                                                                                                                   
                                                                                                                                                                                    
Examples:                                                                                                                                                                           
	| filename                                                                                    | title                                                                          |
	| C:\test\Building a Release Pipeline with Team Foundation Server 2012 - EPUB.epub            | Building a Release Pipeline with Team Foundation Server 2012                   |
	| C:\test\CloudDesignPatternsEPUBebook.epub                                                   | Cloud Design Patterns                                                          |
	| C:\test\DependencyInjectionWithUnity.epub                                                   | Dependency Injection with Unity                                                |
	| C:\test\Deploying an ASP.NET Web Application to a Hosting Provider using Visual Studio.epub | Deploying an ASP.NET Web Application to a Hosting Provider using Visual Studio |
	| C:\test\Deployment-guide-for-SharePoint-2013.epub                                           | Deployment-guide-for-SharePoint-2013                                           |
	| C:\test\Developer's Guide to Microsoft Enterprise Library - 2nd Edition.epub                | Developer's Guide to Microsoft Enterprise Library, 2nd Edition                 |
	| C:\test\Explore-SharePoint-2013.epub                                                        | Explore-SharePoint-2013                                                        |
	| C:\test\Free_Nonfiction_2011.epub                                                           | Free Nonfiction 2011                                                           |
	| C:\test\Free_Nonfiction_2012.epub                                                           | Free Nonfiction 2012                                                           |
	| C:\test\Free_Nonfiction_2013.epub                                                           | Free Nonfiction 2013                                                           |
	| C:\test\Free_Nonfiction_2014.epub                                                           | Free Nonfiction 2014                                                           |
	| C:\test\Free_Stories_2012.epub                                                              | Free Stories 2012                                                              |
	| C:\test\Free_Stories_2013.epub                                                              | Free Short Stories 2013                                                        |
	| C:\test\Free_Stories_2014.epub                                                              | Free Stories 2014                                                              |
	| C:\test\Microsoft_Press_ebook_Introducing_Azure_EPUB.epub                                   | Introducing Windows Azure For IT Professionals                                 |
	| C:\test\Microsoft_Press_ebook_Introducing_Microsoft_SQL_Server_2014_EPUB.epub               | Introducing Microsoft SQL Server 2014 Technical Overview                       |
	| C:\test\Microsoft_Press_ebook_Introducing_System_Center_2012_epub.epub                      | Introducing Microsoft System Center 2012 R2                                    |
	| C:\test\Microsoft_Press_ebook_Introducing_Windows_ITPro_EPUB.epub                           | Introducing Windows 8.1 for IT Professionals                                   |
	| C:\test\Microsoft_Press_ebook_Introducing_Windows_Server_2012_R2_EPUB.epub                  | Introducing Windows Server 2012 R2 Technical Overview                          |
	| C:\test\Microsoft_Press_eBook_Programming_Windows_8_Apps_HTML_CSS_JavaScript_2E_EPUB.epub   | Programming Windows Store Apps with HTML, CSS, and JavaScript                  |
	| C:\test\Microsoft_Press_eBook_Rethinking_Enterprise_Storage_A_Hybrid_Cloud_Model_EPUB.epub  | Rethinking Enterprise Storage: A Hybrid Cloud Model                            |
	| C:\test\Microsoft_Press_ebook_SystemCenterConfMgrFieldExperience_EPUB.epub                  | Microsoft System Center                                                        |
	| C:\test\Microsoft_Press_ebook_SystemCenterDesigningOrchestratorRunbooks_EPUB.epub           | Microsoft System Center Designing Orchestrator Runbooks                        |
	| C:\test\Microsoft_Press_ebook_SystemCenterOptimizingServiceManager_EPUB.epub                | Microsoft System Center Optimizing Service Manager                             |
	| C:\test\Microsoft_System_Center_Integrated_Cloud_Platform_EPUB.epub                         | Microsoftr System Center: Integrated Cloud Platform                            |
	| C:\test\Microsoft_System_Center_Network_Virtualization_and_Cloud_Computing_EPUB.epub        | Microsoft System Center: Network Virtualization and Cloud Computing            |
	| C:\test\Prime_Palaver.epub                                                                  | Prime Palaver                                                                  |
	| C:\test\Reading_Guides_2013.epub                                                            | Reading Guides 2013                                                            |
	| C:\test\SystemCenterBuildingAVirtualizedNetwork_EPUB.epub                                   | Microsoft System Center                                                        |

Scenario Outline: Get ePub content
	Given an ePub file named "<filename>"
	When I open the file using ePubReader
	Then the start of chapter 2 is "<chapter2>"

Examples:
	| filename                                                                                    | chapter2                                                                                                                                                                                                                                                        |
	| C:\test\Building a Release Pipeline with Team Foundation Server 2012 - EPUB.epub            | <?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink">  <head> |
	| C:\test\CloudDesignPatternsEPUBebook.epub                                                   | <?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink">  <head> |
	| C:\test\DependencyInjectionWithUnity.epub                                                   | <?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink">  <head> |
	| C:\test\Deploying an ASP.NET Web Application to a Hosting Provider using Visual Studio.epub | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Deploying an ASP.NET Web Application to a Hosting Provider using |
	| C:\test\Deployment-guide-for-SharePoint-2013.epub                                           | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="Microsoft Word 14 (filtered)" name="Generator"/>    <title>Unknown</title>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>  |
	| C:\test\Developer's Guide to Microsoft Enterprise Library - 2nd Edition.epub                | <?xml version="1.0" encoding="utf-8" standalone="no"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html dir="ltr" xmlns="http://www.w3.org/1999/xhtml" xmlns:xlink="http://www.w3.org/1999/xlink">  <head> |
	| C:\test\Explore-SharePoint-2013.epub                                                        | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="Microsoft Word 14 (filtered)" name="Generator"/>    <title>Unknown</title>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>  |
	| C:\test\Free_Nonfiction_2011.epub                                                           | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta name="Author" content="LJOHNSON"/>    <meta name="Generator" content="Cocoa HTML Writer"/>    <meta name="CocoaVersion" content="1038.35"/>    <meta content |
	| C:\test\Free_Nonfiction_2012.epub                                                           | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Free Nonfiction 2012</title>    <meta content="chc" name="Author"/>    <meta content="Cocoa H |
	| C:\test\Free_Nonfiction_2013.epub                                                           | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Baen Books: Free Nonfiction 2013</title>    <meta content="Jenny Cunningham" name="Author"/>  |
	| C:\test\Free_Nonfiction_2014.epub                                                           | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Free Nonfiction 2014</title>    <meta content="Becky Catchings" name="Author"/>    <meta cont |
	| C:\test\Free_Stories_2012.epub                                                              | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Free Short Stories 2012</title>    <meta content="owner" name="Author"/>    <meta content="Mi |
	| C:\test\Free_Stories_2013.epub                                                              | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Unknown</title>    <meta content="Jenny Cunningham" name="Author"/>    <meta content="Princip |
	| C:\test\Free_Stories_2014.epub                                                              | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Free Stories 2014</title>    <meta content="Becky Catchings" name="Author"/>    <meta content |
	| C:\test\Microsoft_Press_ebook_Introducing_Azure_EPUB.epub                                   | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Introducing Windows Azure For IT Professionals< |
	| C:\test\Microsoft_Press_ebook_Introducing_Microsoft_SQL_Server_2014_EPUB.epub               | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Introducing Microsoft SQL Server 2014 Technical |
	| C:\test\Microsoft_Press_ebook_Introducing_System_Center_2012_epub.epub                      | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Introducing Microsoft System Center 2012 R2</ti |
	| C:\test\Microsoft_Press_ebook_Introducing_Windows_ITPro_EPUB.epub                           | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Introducing Windows 8.1 for IT Professionals</t |
	| C:\test\Microsoft_Press_ebook_Introducing_Windows_Server_2012_R2_EPUB.epub                  | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Introducing Windows Server 2012 R2 Technical Ov |
	| C:\test\Microsoft_Press_eBook_Programming_Windows_8_Apps_HTML_CSS_JavaScript_2E_EPUB.epub   | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Programming Windows Store Apps with HTML, CSS,  |
	| C:\test\Microsoft_Press_eBook_Rethinking_Enterprise_Storage_A_Hybrid_Cloud_Model_EPUB.epub  | <?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:m="http://www.w3.org/1998/Math/MathML" xmlns:pls="http://www.w3.org/2005/01/pronunciation-lexic |
	| C:\test\Microsoft_Press_ebook_SystemCenterConfMgrFieldExperience_EPUB.epub                  | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Microsoft System Center</title><link rel="style |
	| C:\test\Microsoft_Press_ebook_SystemCenterDesigningOrchestratorRunbooks_EPUB.epub           | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Microsoft System Center Designing Orchestrator  |
	| C:\test\Microsoft_Press_ebook_SystemCenterOptimizingServiceManager_EPUB.epub                | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Microsoft System Center</title><link rel="style |
	| C:\test\Microsoft_System_Center_Integrated_Cloud_Platform_EPUB.epub                         | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Microsoftr System Center: Integrated Cloud Plat |
	| C:\test\Microsoft_System_Center_Network_Virtualization_and_Cloud_Computing_EPUB.epub        | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Microsoft System Center: Network Virtualization |
	| C:\test\Prime_Palaver.epub                                                                  | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Unknown</title>    <meta content="Becky Catchings" name="Author"/>    <meta content="Principl |
	| C:\test\Reading_Guides_2013.epub                                                            | <?xml version='1.0' encoding='utf-8'?><html xmlns="http://www.w3.org/1999/xhtml">  <head>    <meta content="text/css" http-equiv="Content-Style-Type"/>    <title>Reading Guides 2013</title>    <meta content="Felecia McDuffie" name="Author"/>    <meta cont |
	| C:\test\SystemCenterBuildingAVirtualizedNetwork_EPUB.epub                                   | <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html xml:lang="en-gb" xmlns="http://www.w3.org/1999/xhtml"><head><title>Microsoft System Center</title><link rel="style |

Scenario Outline: Get ePub text content
	Given an ePub file named "<filename>"
	When I open the file using ePubReader
	Then the text start of chapter 2 is "<chapter2>"

Examples:
	| filename                                                                                    | chapter2                                                                                                                                                                                                                                                       |
	| C:\test\Building a Release Pipeline with Team Foundation Server 2012 - EPUB.epub            | Contents       Summary    Foreword by Anutthara Bharadwaj    1 – You Want It When?    2 – The Beginning    3 – Orchestrating the Release Pipeline    4 – Automating the Release Pipeline    5 – Getting Good Feedback    6 – Improving the Pipeline    Appen   |
	| C:\test\CloudDesignPatternsEPUBebook.epub                                                   | Contents        Preface    Patterns    Cache-aside Pattern    Circuit Breaker Pattern    Compensating Transaction Pattern    Competing Consumers Pattern    Compute Resource Consolidation Pattern    Command and Query Responsibility Segregation (CQRS) Pa   |
	| C:\test\DependencyInjectionWithUnity.epub                                                   | Copyright      This document is provided “as-is”. Information and views expressed in this document, including URL and other Internet Web site references, may change without notice.  Some examples depicted herein are provided for illustration only and a   |
	| C:\test\Deploying an ASP.NET Web Application to a Hosting Provider using Visual Studio.epub | Deploying an ASP.NET Web Application to a Hosting Provider using Visual Studio  Tom Dykstra  Summary: This series of tutorials shows you how to make an ASP.NET web application available over the internet by deploying it to a third-party hosting provider  |
	| C:\test\Deployment-guide-for-SharePoint-2013.epub                                           | Add a RefinementWeb Part to a page  You can addrefiners to a page to narrow the items that are shown in a Content Search WebPart, and help users quickly browse to specific content. Refiners are based onmanaged properties from the search index. To displa  |
	| C:\test\Developer's Guide to Microsoft Enterprise Library - 2nd Edition.epub                | Contents       Foreword by S. Somasegar    Foreword to the 1st Edition by Scott Guthrie    1 - Welcome to the Library: Introduction to the Microsoft Enterprise Library    2 - Much ADO about Data Access: Using the Data Access Application Block     3 - E   |
	| C:\test\Explore-SharePoint-2013.epub                                                        | Abstract  This book provides information about what's new in SharePoint 2013.The audiences for this book include application specialists, line-of-businessapplication specialists, and IT administrators who want to know more aboutSharePoint 2013.  The con  |
	| C:\test\Free_Nonfiction_2011.epub                                                           | Terraforming Ganymede with Robert A. Heinlein by Gregory Benford     Discovering Heinlein, for most who have, is like having sex or dropping acid: you don’t forget your first time.  – Adrienne Martini , Locus 2011    There it is. Gosh, $2.50. But ... I   |
	| C:\test\Free_Nonfiction_2012.epub                                                           | Putting the Science in Science Fiction by Tedd Roberts   Thirty-five years ago I entered college with a plan: I would major in pre-med, go to medical school, study neurosurgery and specialize in bionics.  It was 1976 and The Six Million Dollar Man had b  |
	| C:\test\Free_Nonfiction_2013.epub                                                           | On the Road to the Brainships: A Look at the Current Science of Interfacing the Brain   by Tedd Roberts  There are many science fiction (SF) stories in which the characters have some form of direct brain-to-computer connection, but none quite rivals      |
	| C:\test\Free_Nonfiction_2014.epub                                                           | Training for War, Part IV  by Tom Kratman   Vignette Seven: oh, of course the enemy will always set himself up for maximum vulnerability to your drills and standard operating procedures.  (The following is extracted from Carnifex , Volume II in the Car   |
	| C:\test\Free_Stories_2012.epub                                                              | Grayson Navy Letters Home by Joelle Presby  (artwork by Thomas Pope)    [Post to Tester’s Blessings on the GSN private forum.] [October 1921]  Everyone, Ladies, and Whoever,  My sister, Ensign Cecelie Rustin, Grayson Navy sent this. Cecelie just got her  |
	| C:\test\Free_Stories_2013.epub                                                              | Seven Miles   by T.C. McCarthy   Kostya held his breath. When the airlock door hissed open, the suit's scanner whined to life.  "Clear," its voice chimed.  "Come." He adjusted the incinerator straps, flicked off the safety, and angled his body so tha     |
	| C:\test\Free_Stories_2014.epub                                                              | The Aristocrat and the Free Man  by Robert Conroy   My latest novel, Liberty: 1784 , takes place in a dark world where the British have won the Revolution and are hell bent on imposing a harsh regime mirroring England’s. This is a short story dealing w   |
	| C:\test\Microsoft_Press_ebook_Introducing_Azure_EPUB.epub                                   | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2013 Microsoft Corporation  All rights reserved. No part of the contents of this book may be reproduced or transmitted in any fo  |
	| C:\test\Microsoft_Press_ebook_Introducing_Microsoft_SQL_Server_2014_EPUB.epub               | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2014 by Microsoft Corporation  All rights reserved. No part of the contents of this book may be reproduced or transmitted in any  |
	| C:\test\Microsoft_Press_ebook_Introducing_System_Center_2012_epub.epub                      | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2013 Microsoft Corporation  All rights reserved. No part of the contents of this book may be reproduced or transmitted in any fo  |
	| C:\test\Microsoft_Press_ebook_Introducing_Windows_ITPro_EPUB.epub                           | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2013 Microsoft Corporation  All rights reserved. No part of the contents of this book may be reproduced or transmitted in any fo  |
	| C:\test\Microsoft_Press_ebook_Introducing_Windows_Server_2012_R2_EPUB.epub                  | Contents  Introduction  Chapter 1 Cloud OS  The big picture  Journey to the Cloud OS  Let s begin!  Chapter 2 Hyper-V  Previous enhancements to Hyper-V  Generation 2 virtual machines  Automatic Virtual Machine Activation  Remote access over VMBus  Cross  |
	| C:\test\Microsoft_Press_eBook_Programming_Windows_8_Apps_HTML_CSS_JavaScript_2E_EPUB.epub   | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2014Microsoft Corporation  All rights reserved. No part of the contents of this book may be reproduced or transmitted in any for  |
	| C:\test\Microsoft_Press_eBook_Rethinking_Enterprise_Storage_A_Hybrid_Cloud_Model_EPUB.epub  | Foreword When I started my career in IT, storage was incredibly boring and something that most people tried to avoid. Enterprise data storage was the domain of strange people interested in tracks, cylinders, and data placements; they did not write code—t |
	| C:\test\Microsoft_Press_ebook_SystemCenterConfMgrFieldExperience_EPUB.epub                  | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2013 by Microsoft Corporation (All)  All rights reserved. No part of the contents of this book may be reproduced or transmitted   |
	| C:\test\Microsoft_Press_ebook_SystemCenterDesigningOrchestratorRunbooks_EPUB.epub           | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2013 Microsoft Corporation  All rights reserved. No part of the contents of this book may be reproduced or transmitted in any fo  |
	| C:\test\Microsoft_Press_ebook_SystemCenterOptimizingServiceManager_EPUB.epub                | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399 Copyright 2013 by Microsoft Corporation (All) All rights reserved. No part of the contents of this book may be reproduced or transmitted in  |
	| C:\test\Microsoft_System_Center_Integrated_Cloud_Platform_EPUB.epub                         | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2014 Microsoft Corporation (All)  All rights reserved. No part of the contents of this book may be reproduced or transmitted in   |
	| C:\test\Microsoft_System_Center_Network_Virtualization_and_Cloud_Computing_EPUB.epub        | PUBLISHED BY Microsoft Press A Division of Microsoft Corporation One Microsoft Way Redmond, Washington 98052-6399  Copyright 2014 by Microsoft Corporation (All)  All rights reserved. No part of the contents of this book may be reproduced or transmitted   |
	| C:\test\Prime_Palaver.epub                                                                  | Prime Palaver # 2  Letters to the Librarian  Eric Flint  January 16, 2000   Since an article got published in slashdot.org, the Library has been flooded with hits and I received about 200 letters within 24 hours.  But even before that happened, I was r   |
	| C:\test\Reading_Guides_2013.epub                                                            | Teacher’s Guide to Rising Sun      Contents:   recommended reading level  plot summary  character sketches  guides to each chapter, including: 	 	 prepare to read… 		 	 	 vocabulary 			 focus questions and initiating activities 			 suggested “supportive  |
	| C:\test\SystemCenterBuildingAVirtualizedNetwork_EPUB.epub                                   | Contents  Introduction  Chapter 1 Key concepts  Introducing Contoso Ltd  Architecture  Virtualized network components  Logical network  IP and MAC address pools  Uplink port profiles  Network adapter port profiles  Port classifications  Logical switches  |
